### ISSUE TITLE
Operator fails on invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ahadas** [observatorium/observatorium#270]
It looks like some kind of race that resulted in:
```
[admin@spoke1 configuration]$ oc -n observatorium logs observatorium-operator-6ff57f6b77-7vvpq
W0510 15:09:32.528320       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ts=2020-05-10T15:09:33.233019951Z caller=resource.go:123 msg="resources trigger started"
level=debug ts=2020-05-10T15:09:33.324971608Z caller=handlers.go:124 resource-handler=obs action=add key=openshift-monitoring/observatorium-xyz
level=debug ts=2020-05-10T15:09:33.325189766Z caller=handlers.go:127 resource-handler=obs msg="transformed key" original-key=openshift-monitoring/observatorium-xyz new-key=openshift-monitoring/observatorium-xyz
level=debug ts=2020-05-10T15:09:33.325392506Z caller=handlers.go:124 resource-handler=obs action=add key=observatorium/observatorium-xyz
level=debug ts=2020-05-10T15:09:33.325480897Z caller=handlers.go:127 resource-handler=obs msg="transformed key" original-key=observatorium/observatorium-xyz new-key=observatorium/observatorium-xyz
ts=2020-05-10T15:09:33.325461273Z caller=resource.go:185 msg="sync triggered" key=openshift-monitoring/observatorium-xyz
level=debug ts=2020-05-10T15:09:50.926212928Z caller=feedback.go:101 msg="initializing status" namespace=openshift-monitoring name=observatorium-xyz kind=Observatorium apiVersion=core.observatorium.io/v1alpha1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11a7261]

goroutine 219 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetResourceVersion(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.18.2/pkg/apis/meta/v1/unstructured/unstructured.go:282
github.com/brancz/locutus/client.(*ResourceClient).prepareUnstructuredForUpdate(0xc004ee3a10, 0x0, 0xc000667c48, 0x2, 0x0)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/client/client.go:141 +0x41
github.com/brancz/locutus/client.(*ResourceClient).UpdateWithCurrent(0xc004ee3a10, 0x0, 0xc000667c48, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/client/client.go:135 +0x5a
github.com/brancz/locutus/rollout.(*CreateOrUpdateObjectAction).Execute(0x234a820, 0xc004ee3a10, 0xc000667c48, 0x0, 0x0)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/rollout/actions.go:34 +0x252
github.com/brancz/locutus/rollout.(*RolloutRunner).executeSingleAction(0xc00029c410, 0xc002d08c20, 0xe, 0xc000667c48, 0x234bc40, 0x175ba00)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/rollout/rollout.go:171 +0xd0
github.com/brancz/locutus/rollout.(*RolloutRunner).executeAction(0xc00029c410, 0xc002d08c20, 0xe, 0xc000667c48, 0x1, 0xa20000000156c93b)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/rollout/rollout.go:161 +0x9a
github.com/brancz/locutus/rollout.(*RolloutRunner).runStep(0xc00029c410, 0xc0037cfe40, 0xc000667c48, 0xe, 0xc0004bd3c0)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/rollout/rollout.go:143 +0x56
github.com/brancz/locutus/rollout.(*RolloutRunner).Execute(0xc00029c410, 0xc00021fda0, 0x0, 0x0)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/rollout/rollout.go:126 +0x3a0
github.com/brancz/locutus/config.(*ConfigPasser).Execute(0xc00042d320, 0xc00021fda0, 0x40e768, 0x30)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/config/config.go:34 +0x97
github.com/brancz/locutus/trigger/types.(*ExecutionRegister).Execute(0xc0004046c0, 0xc00021fda0, 0xc00046c600, 0x11fd)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/trigger/types/types.go:40 +0x6f
github.com/brancz/locutus/trigger/resource.(*ResourceTrigger).sync(0xc0004046c0, 0xc0003c6600, 0x26, 0x0, 0x10ca100)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/trigger/resource/resource.go:200 +0x2cf
github.com/brancz/locutus/trigger/resource.(*ResourceTrigger).processNextWorkItem(0xc0004046c0, 0xc0005d4f00)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/trigger/resource/resource.go:172 +0x100
github.com/brancz/locutus/trigger/resource.(*ResourceTrigger).worker(0xc0004046c0)
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/trigger/resource/resource.go:161 +0x2b
created by github.com/brancz/locutus/trigger/resource.(*ResourceTrigger).Run
	/go/pkg/mod/github.com/brancz/locutus@v0.0.0-20200430073700-65b7640ed9bc/trigger/resource/resource.go:125 +0x107
```

**Comment by brancz** [comment]
Sounds like this might be a bug on locutus?

**Comment by ahadas** [comment]
Yeah, looks like that.... :/

**Comment by bwplotka** [comment]
Let's move this issue to https://github.com/brancz/locutus then 🤗 Thanks!
